Repository FRONTENDSCHOOL5/final-13-NuTalent, pull requests merged in 2023-07, with the labels that each got.

#170 155 [ProfileDetail] 게시글 랜더링 오류 수정
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
Labels: 🐞 버그

#171 165 [Post] z-index 수정
  src/components/common/Top/TopUploadNav.styled.js
Labels: 🐞 버그

#172 164 [Post] 프로필 사진 적용 오류 수정
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Post/PostUpload/PostUpload.styled.js
Labels: 🐞 버그

#175 160 [TopBasicNav] 모달 항목 변경
  src/components/common/Top/TopBasicNav.jsx
Labels: 🎨 마크업&스타일링

#178 152 [공통] 이미지 오류 onError 처리
  src/components/common/User/User.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Profile/Follower/FollowerUser.jsx
  src/pages/Profile/Following/FollowingUser.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Search/Search.jsx
  src/util/handleImageError.js
Labels: 🐞 버그

#179 154 [공통] package.json 프로젝트 이름 수정
  package.json
Labels: 📁문서 수정

#180 166 [PostEdit] 스크롤 오류 수정
  src/components/common/BottomSheetModal/BottomSheetModal.jsx
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
Labels: 🐞 버그

#184 167 [Login] 유효성 검사 방식 수정
  src/pages/Auth/SignUp/SignUp.jsx
Labels: ✒ 리팩토링

#185 157 [Chat] 채팅 페이지 랜더링 오류 수정
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
Labels: 🧱 기능 구현

#198 190 리액트 쿼리 도입
  .eslintrc
  package.json
  src/App.js
  src/hooks/react-query/useFollow.js
  src/hooks/react-query/useImage.js
  src/hooks/react-query/usePost.js
  src/hooks/react-query/useProduct.js
  src/hooks/react-query/useProfile.js
  src/index.js
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/util/api/axiosInstance.js
  src/util/queryClient.js
  yarn.lock
Labels: 🛠 개발 환경 세팅, 🧱 기능 구현, ✒ 리팩토링
