Repository FRONTENDSCHOOL5/final-13-NuTalent, pull requests merged in 2023-09, with the labels that each got.

#233 232 [Post] 게시글 업로드 페이지 이미지 비율 문제 수정
  src/pages/Post/PostEdit/PostEdit.styled.js
  src/pages/Post/PostUpload/PostUpload.styled.js
Labels: 🐞 버그

#234 231 [PostItem] 줄 바꿈 처리 안 되는 버그 수정
  src/components/common/PostItem/PostItem.styled.js
Labels: 🐞 버그

#235 Feature/217 topnav 컴포넌트 리팩토링
  src/components/common/Top/TopBasicNav.jsx
  src/components/common/Top/TopBasicNav.styled.js
  src/components/common/Top/TopChatNav.jsx
  src/components/common/Top/TopChatNav.styled.js
  src/components/common/Top/TopMainNav.jsx
  src/components/common/Top/TopMainNav.styled.js
  src/components/common/Top/TopNav.jsx
  src/components/common/Top/TopNav.styled.js
  src/components/common/Top/TopSearchNav.jsx
  src/components/common/Top/TopSearchNav.styled.js
  src/components/common/Top/TopUploadNav.jsx
  src/components/common/Top/TopUploadNav.styled.js
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Home/Home.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Product/ProductEdit/ProductEdit.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/Following/Following.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/pages/Search/Search.jsx
Labels: ✒ 리팩토링

#240 202 [post,home,product]리액트 쿼리 도입
  src/hooks/react-query/useComment.js
  src/hooks/react-query/usePost.js
  src/hooks/react-query/useProduct.js
  src/pages/Home/Home.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Product/ProductEdit/ProductEdit.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
Labels: ✒ 리팩토링

#239 238 [Search] 쿼리 인스턴스 상태 변경
  src/hooks/react-query/useSearch.js
Labels: 🎭 최적화

#236 230 [Splash] 디자인 변경
  src/assets/img/peo1.png
  src/assets/img/peo2.png
  src/assets/img/peo3.png
  src/assets/img/peo4.png
  src/assets/img/peo5.png
  src/pages/Auth/Intro/intro.styled.js
  src/pages/Splash/Splash.jsx
  src/pages/Splash/Splash.styled.js
Labels: 🎨 마크업&스타일링

#242 Feature/241 postitem 리액트 쿼리 도입
  src/components/Toast/Toast.jsx
  src/components/common/Alert/Alert.jsx
  src/components/common/BottomSheetModal/BottomSheetModal.jsx
  src/components/common/PostItem/PostItem.jsx
  src/components/common/PostItem/PostItem.styled.js
  src/components/common/User/User.styled.js
  src/hooks/react-query/useComment.js
  src/hooks/react-query/useLike.js
  src/hooks/react-query/usePost.js
  src/pages/Home/Home.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Product/ProductEdit/ProductEdit.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
Labels: ✒ 리팩토링
