Repository FRONTENDSCHOOL5/final-13-NuTalent, pull requests merged in 2023-06, with the labels that each got.

#2 초기 환경 세팅
  .eslintignore
  .eslintrc
  .prettierignore
  .prettierrc
  package.json
  src/App.js
  src/assets/img/Google__G__Logo 1.svg
  src/assets/img/basic-profile-img-.svg
  src/assets/img/basic-profile.svg
  src/assets/img/facebook.svg
  src/assets/img/iccon-img-layers.svg
  src/assets/img/icon- more-vertical.svg
  src/assets/img/icon-arrow-left.svg
  src/assets/img/icon-edit.svg
  src/assets/img/icon-heart.svg
  src/assets/img/icon-home-fill.svg
  src/assets/img/icon-home.svg
  src/assets/img/icon-image.svg
  src/assets/img/icon-message-circle-1.svg
  src/assets/img/icon-message-circle-fill.svg
  src/assets/img/icon-message-circle.svg
  src/assets/img/icon-post-album-off.svg
  src/assets/img/icon-post-album-on.svg
  src/assets/img/icon-post-list-off.svg
  src/assets/img/icon-post-list-on.svg
  src/assets/img/icon-search.svg
  src/assets/img/icon-share.svg
  src/assets/img/icon-user-fill.svg
  src/assets/img/icon-user.svg
  src/assets/img/img-button.svg
  src/assets/img/message-circle.svg
  src/assets/img/s-icon-more-vertical.svg
  src/assets/img/upload-file.svg
  src/assets/img/x.svg
  src/components/common/.gitkeep
  src/components/footer/.gitkeep
  src/components/header/.gitkeep
  src/components/login/.gitkeep
  src/hooks/.gitkeep
  src/pages/.gitkeep
  src/recoil/atoms/.gitkeep
  src/recoil/selectors/.gitkeep
  src/routes/.gitkeep
  src/styles/GlobalStyle.js
  yarn.lock
Labels: enhancement

#4 3 템플릿 설정
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#7 6 Tab-Menu 공통 컴포넌트 구현
  src/components/common/.gitkeep
  src/components/common/Tabmenu/TabMenu.jsx
  src/components/common/Tabmenu/TabMenu.styled.js
Labels: enhancement, good first issue

#14 Feat: TextActiveInput 공통 컴포넌트 구현 (#13)
  src/components/common/TextActiveInput/TextActiveInput.jsx
  src/components/common/TextActiveInput/TextActiveInput.styled.js
Labels: enhancement

#19 Feat: Product 공통 컴포넌트 구현 (#18)
  src/components/common/Product/ProductItem.jsx
Labels: enhancement

#20 Feat: 로그인 페이지 ui 구현 (#17)
  src/pages/.gitkeep
  src/pages/LoginPage.jsx
  src/pages/LoginPage.styled.js
Labels: enhancement

#22 Feat: 404 페이지 UI 구현 (#21)
  src/pages/404/NotFound.jsx
Labels: enhancement

#23 #9 글로벌 스타일 적용
  src/index.js
  src/styles/GlobalStyle.js
Labels: enhancement

#27 Feat: 공통 컴포넌트 구현
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/Alert.styled.js
  src/components/common/Post/Post.jsx
  src/components/common/Post/Post.styled.js
  src/components/common/User/User.jsx
  src/components/common/User/User.styled.js
Labels: 🧱 기능 구현

#33 24 로그인 페이지 기능 구현
  src/components/common/TextActiveInput/TextActiveInput.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Login/LoginPage.styled.js
  src/pages/LoginPage.jsx
  src/util/api/axiosInstance.js
Labels: 🧱 기능 구현

#32 Refactor: 공통 컴포넌트 리팩터링
  src/assets/img/icon-more-vertical.svg
  src/components/common/Alert/Alert.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.styled.js
  src/components/common/Button/LButton.jsx
  src/components/common/Button/LButton.styled.js
  src/components/common/Button/MButton.jsx
  src/components/common/Button/MButton.styled.js
  src/components/common/Button/MsButton.jsx
  src/components/common/Button/MsButton.styled.js
  src/components/common/Button/SButton.jsx
  src/components/common/Button/SButton.styled.js
  src/components/common/Post/Post.styled.js
  src/components/common/Product/ProductItem.jsx
  src/components/common/Tabmenu/TabMenu.jsx
  src/components/common/Tabmenu/TabMenu.styled.js
  src/components/common/TextActiveInput/TextActiveInput.jsx
  src/components/common/Top/TopBasicNav.jsx
  src/components/common/Top/TopChatNav.jsx
  src/components/common/Top/TopMainNav.jsx
  src/components/common/Top/TopSearchNav.jsx
  src/components/common/Top/TopUploadNav.jsx
  src/styles/GlobalStyle.js
Labels: ✒ 리팩토링

#31 Feat: 회원가입 페이지 기능 구현 (#26)
  src/App.js
  src/pages/JoinMembers/JoinMembers.jsx
  src/pages/JoinMembers/JoinMembers.styled.js
Labels: 🧱 기능 구현

#37 Feat: 게시글 작성 페이지 구현
  src/components/common/Top/TopUploadNav.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.styled.js
  src/util/imageValidation.js
Labels: 🧱 기능 구현

#39 Feat: 하단 모달창 컴포넌트 구현
  src/components/common/BottomSheetModal/BottomSheetModal.jsx
  src/components/common/BottomSheetModal/BottomSheetModal.styled.js
Labels: 🎨 마크업&스타일링

#48 43 회원가입 프로필 설정 기능 구현
  src/pages/Auth/Login/Login.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.styled.js
  src/pages/Auth/SignUp/SignUp.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.styled.js
Labels: 🧱 기능 구현

#49 38 Profile 페이지 구현
  src/components/common/Top/TopBasicNav.styled.js
  src/components/common/Top/TopChatNav.styled.js
  src/components/common/Top/TopMainNav.styled.js
  src/components/common/Top/TopSearchNav.styled.js
  src/components/common/Top/TopUploadNav.styled.js
Labels: 🎨 마크업&스타일링

#55 50 프로필 설정 페이지 기능 구현
  src/components/common/Top/TopUploadNav.styled.js
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.styled.js
Labels: 🧱 기능 구현

#57 56 로그인 및 회원가입 페이지 리팩토링
  src/pages/Auth/Login/Login.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Labels: ✒ 리팩토링

#62 58 Splash 페이지 연결
  src/pages/Splash/Splash.jsx
  src/pages/Splash/Splash.styled.js
Labels: 🧱 기능 구현

#64 51 Profile 페이지 기능 구현
  src/hooks/useScrollBottom.js
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
  src/routes/Router.jsx
Labels: 🧱 기능 구현

#66 63 Search 페이지 구현
  src/components/common/Top/TopSearchNav.jsx
  src/components/common/Top/TopSearchNav.styled.js
  src/components/common/User/User.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.styled.js
  src/pages/Auth/SignUp/SignUp.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.styled.js
  src/pages/Search/Search.jsx
  src/pages/Search/Search.styled.js
  src/pages/Splash/Splash.jsx
Labels: 🎨 마크업&스타일링, 🧱 기능 구현

#73 65 채팅 페이지 UI 구현
  src/components/common/Top/TopChatNav.styled.js
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatList/ChatList.styled.js
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.styled.js
Labels: 🎨 마크업&스타일링

#78 77 Profile 페이지 팔로우 기능 추가
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
Labels: 🧱 기능 구현

#80 74 Following 목록 페이지 구현
  src/pages/Profile/Following/Following.jsx
  src/pages/Profile/Following/Following.styled.js
  src/pages/Profile/Following/FollowingUser.jsx
  src/pages/Profile/Following/FollowingUser.styled.js
  src/routes/Router.jsx
Labels: 🧱 기능 구현

#83 81 앱 전반 보강 및 업데이트
  src/components/common/Tabmenu/TabMenu.jsx
  src/components/common/Top/TopBasicNav.jsx
  src/components/common/Top/TopChatNav.jsx
  src/components/common/Top/TopSearchNav.jsx
  src/components/common/Top/TopUploadNav.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Post/PostUpload/PostUpload.styled.js
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.styled.js
  src/pages/선근/선근.jsx
Labels: 🧱 기능 구현, ✒ 리팩토링

#91 86 Follow/Following 페이지에 Follow 기능 추가
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/Follower/FollowerUser.jsx
  src/pages/Profile/Follower/FollowerUser.styled.js
  src/pages/Profile/Following/Following.jsx
  src/pages/Profile/Following/FollowingUser.jsx
  src/pages/Profile/Following/FollowingUser.styled.js
Labels: 🧱 기능 구현

#90 67 Recoil 도입하여 전역 상태 관리 및 라우터 수정
  src/App.js
  src/components/common/PostItem/PostItem.jsx
  src/components/common/Tabmenu/TabMenu.jsx
  src/components/common/User/User.jsx
  src/pages/Auth/Login/Login.jsx
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatList/ChatList.styled.js
  src/pages/Home/Home.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/recoil/atoms/.gitkeep
  src/recoil/atoms/dataState.js
  src/recoil/atoms/loginState.js
  src/recoil/effects/loginStateEffect.js
  src/recoil/selectors/dataStateSelector.js
Labels: 🧱 기능 구현, ✒ 리팩토링, 🎭 최적화

#95 92 팔로우, 팔로잉 페이지 recoil로 데이터 받아오기
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/Following/Following.jsx
Labels: ✒ 리팩토링

#97 96 게시글 날짜 표시 형태 변경
  src/components/common/PostItem/PostItem.jsx
Labels: ✒ 리팩토링

#99 93 채팅목록 및 채팅방 스타일링 수정
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatList/ChatList.styled.js
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.styled.js
Labels: 🎨 마크업&스타일링

#104 101 좋아요 버튼 활성화 상태일 때 색상 바뀌도록 구현
  src/assets/img/Active-icon-heart.svg
  src/components/common/PostItem/PostItem.jsx
  src/components/common/PostItem/PostItem.styled.js
Labels: 🧱 기능 구현

#105 103 ProductEdit 페이지 구현
  src/pages/Product/ProductEdit/ProductEdit.jsx
  src/pages/Product/ProductEdit/ProductEdit.styled.js
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/routes/Router.jsx
Labels: 🧱 기능 구현

#110 69 유저 검색 페이지 최적화
  package.json
  src/pages/Chat/ChatRoom/ChatRoom.styled.js
  src/pages/Search/Search.jsx
Labels: 🎭 최적화

#112 107 팔로워,팔로잉 페이지 각 목록에 유저 프로필 연결
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/Following/Following.jsx
Labels: ✒ 리팩토링

#113 111 프로필 수정 후 전역 데이터에 데이터 업데이트
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Labels: 🧱 기능 구현, 🐞 버그

#116 111 프로필 수정 후 리코일에 데이터 업데이트
  src/components/common/ProductItem/ProductItem.jsx
  src/components/common/ProductItem/ProductItem.styled.js
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
Labels: 🎨 마크업&스타일링

#115 108 bottom sheet와 alert 모달 구현
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/Alert.styled.js
  src/components/common/BottomSheetModal/BottomSheetModal.jsx
  src/components/common/BottomSheetModal/BottomSheetModal.styled.js
  src/components/common/PostItem/PostItem.jsx
  src/components/common/ProductItem/ProductItem.jsx
  src/components/common/Top/TopBasicNav.jsx
  src/hooks/useScrollBottom.js
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
Labels: 🧱 기능 구현

#118 117 404페이지 뒤로가기 기능 추가
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/NotFound/NotFound.jsx
Labels: 🧱 기능 구현

#129 119 유효성 검사 코드 수정
  src/pages/Auth/Login/Login.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/Auth/ProfileSetting/ProfileSetting.styled.js
  src/pages/Auth/SignUp/SignUp.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.styled.js
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Labels: ✒ 리팩토링

#123 122 PrivateRoute 구현
  src/routes/PrivateRoute.jsx
  src/routes/Router.jsx
Labels: 🧱 기능 구현

#124 121 앱 전반 버그 수정
  src/pages/Product/ProductEdit/ProductEdit.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
Labels: 🐞 버그

#131 130 댓글/ 포스트 신고하기 api 추가
  src/components/common/PostItem/PostItem.jsx
  src/pages/Post/PostDetail/PostDetail.jsx
Labels: 🎨 마크업&스타일링, 🧱 기능 구현

#133 132 폴더 구조 정리
  package-lock.json
  src/components/footer/.gitkeep
  src/components/header/.gitkeep
  src/components/login/.gitkeep
  src/hooks/.gitkeep
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Product/ProductUpload/ProductUpload.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
  src/recoil/selectors/.gitkeep
  src/recoil/selectors/dataStateSelector.js
  src/util/validation/imageValidation.js
Labels: 📁문서 수정

#137 127 리드미 작성
  README.md
Labels: 📁문서 수정

#145 Netlify redirects파일 추가
  public/_redirects
Labels: 🐞 버그
