Repository FRONTENDSCHOOL5/final-13-NuTalent, pull requests merged in 2023-08, with the labels that each got.

#204 199 [modal] 컴포넌트 리팩터링
  src/App.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.styled.js
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.styled.js
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/Alert.styled.js
  src/components/common/BottomSheetModal/BottomSheetModal.jsx
  src/components/common/BottomSheetModal/BottomSheetModal.styled.js
  src/components/common/PostItem/PostItem.jsx
  src/components/common/ProductItem/ProductItem.jsx
  src/components/common/Top/TopBasicNav.jsx
  src/components/common/Top/TopChatNav.jsx
  src/components/common/Transition/Transition.jsx
  src/components/common/Transition/Transition.styled.js
  src/hooks/useCloseAfterTransition.js
  src/hooks/useModal.js
  src/pages/Post/PostDetail/PostDetail.jsx
  src/recoil/atoms/modalState.js
  src/routes/Router.jsx
Labels: ✒ 리팩토링

#207 201 [ProfileEdit] 리액트쿼리 도입
  src/hooks/react-query/useProfile.js
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Labels: ✒ 리팩토링

#209 208 [follower, following] accountname 받는 방법 수정
  src/pages/Profile/Follower/Follower.jsx
  src/pages/Profile/Following/Following.jsx
  src/pages/Profile/ProfileDetail/ProfileDetail.jsx
  src/routes/Router.jsx
Labels: ✒ 리팩토링

#212 Feature/210 게시글 태그 기능 구현
  src/components/common/PostItem/PostItem.jsx
  src/components/common/TagBar/TagBar.jsx
  src/components/common/TagBar/TagBar.styled.js
  src/hooks/useTag.js
  src/pages/Home/Home.jsx
  src/pages/Home/Home.styled.js
  src/pages/Post/PostEdit/PostEdit.jsx
  src/pages/Post/PostEdit/PostEdit.styled.js
  src/pages/Post/PostUpload/PostUpload.jsx
  src/pages/Post/PostUpload/PostUpload.styled.js
Labels: 🧱 기능 구현

#215 214 팔로우/팔로잉 버그 수정
  src/hooks/react-query/useFollow.js
Labels: 🐞 버그

#216 213 이미지 캐러셀 구현
  src/components/common/Carousel/Carousel.jsx
  src/components/common/Carousel/Carousel.styled.js
  src/components/common/PostItem/PostItem.jsx
  src/components/common/PostItem/PostItem.styled.js
Labels: 🧱 기능 구현

#219 Fix: 태그 없는 게시글 수정 시 에러 수정 (#218)
  src/hooks/useTag.js
Labels: 🐞 버그

#222 221 [ProfileSetting] 리액트 쿼리 도입
  src/hooks/react-query/useAuth.js
  src/pages/Auth/ProfileSetting/ProfileSetting.jsx
Labels: ✒ 리팩토링

#226 225 [Search] 리액트 쿼리 도입
  package.json
  src/hooks/react-query/useSearch.js
  src/pages/Search/Search.jsx
Labels: ✒ 리팩토링

#227 223 [Login] 리액트 쿼리 도입
  src/hooks/react-query/useAuth.js
  src/pages/Auth/Login/Login.jsx
Labels: ✒ 리팩토링
